config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :movies

  resources :video_games

  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
	validates :title, presence: true
  	validates :author, presence: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @book = Book.new
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        # format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.html { redirect_to books_url }
        format.json { render :show, status: :created, location: @book }
        format.js   { render action: 'show', status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
        format.js   { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :read, :description, :digital, :release_date, :pages, :link, :big_image, :small_image)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        # format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.html { redirect_to movies_url }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :sd, :hd, :threed, :digital, :watched)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_search.html.erb
<div id="search">
	<form>
		<input id="livesearch_query" type="text" size="30" onkeyup="showResult(this.value)", class="form-control">
		<div id="livesearch_results"></div>
	</form>
</div>

<div id="createBook" style="display: none;">
	<table width="100%" style="margin-bottom: 20px;">
		<tr>
			<td>
				<img id="bookBigImage" src=""/>
			</td>
			<td width="100%">
				<h1 id="bookTitle" />
				<h2 id="bookAuthor" />
			</td>
		</tr>
	</table>

	<% modal ||= false %>
	<% remote = modal ? true : false %>
	<%= form_for(@book, remote: remote, html: {role: :form, 'data-model' => 'book'}) do |f| %>
	  <% if @book.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

	      <ul>
	      <% @book.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <!-- Values are set in books.js -->
	  <%= f.hidden_field :title %>
	  <%= f.hidden_field :author %>
	  <%= f.hidden_field :description %>
	  <%= f.hidden_field :pages %>
	  <%= f.hidden_field :release_date %>
	  <%= f.hidden_field :link %>
	  <%= f.hidden_field :small_image %>
	  <%= f.hidden_field :big_image %>

	  <div class="form-group">
	    <%= f.label :read, class: 'control-label' %><br>
	    <%= f.check_box :read, class: 'form-control' %>
	    <span class="help-block"></span>
	  </div>
	  <div class="form-group">
	    <%= f.label :digital, class: 'control-label' %><br>
	    <%= f.check_box :digital, class: 'form-control' %>
	    <span class="help-block"></span>
	  </div>
	  <div class="actions">
	    <%= f.submit class: 'btn btn-large btn-primary' %>
	  </div>
	<% end %>
</div>

app/views/books/_table_row.html.erb
<tr>
  <td width="55px"><%= image_tag(book.small_image) %></td>
  <td><%= book.title %></td>
  <td><%= book.author %></td>
  <td><% if book.read %><div class="glyphicon glyphicon-ok"></div><% end %></td>
  <td width="25px"><%= link_to '', book, class: 'glyphicon glyphicon-eye-open' %></td>
  <td width="25px"><%= link_to '', edit_book_path(book), class: 'glyphicon glyphicon-pencil' %></td>
  <td width="25px"><%= link_to '', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'glyphicon glyphicon-trash' %></td>
</tr>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table class="table table-striped" id='books_table'>
  <thead>
    <tr>
      <th/>
      <th>Title</th>
      <th>Author</th>
      <th>Read</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <%= render partial: 'table_row', locals: {book: book} %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', '#search_modal', 'data-toggle' => 'modal', :onclick=>"showModal()", class: 'btn btn-large btn-primary' %>

<div class="modal fade" id="search_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Find a book</h4>
      </div>
      <div class="modal-body">
        <%# Render the new book form (passing modal => true to enable remote => true) %>
        <%= render partial: 'search', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to '<< Back', books_path, :class => "btn btn-large" %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Read:</strong>
  <%= @book.read %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/show.js.erb
$('#books_table').append("<%= j render partial: 'table_row', locals: {book: @book } %>");
$('#new_book_modal').modal_success();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Catalog</title>

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>
<body>

  <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to 'Catalog', root_path, id: "logo" %>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :sd %><br>
      <%= f.check_box :sd, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :hd %><br>
      <%= f.check_box :hd, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :threed %><br>
      <%= f.check_box :threed, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :digital %><br>
      <%= f.check_box :digital, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :watched %><br>
      <%= f.check_box :watched, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit class: 'btn btn-large btn-primary' %>
    </div>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Sd</th>
      <th>Hd</th>
      <th>Threed</th>
      <th>Digital</th>
      <th>Watched</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.sd %></td>
        <td><%= movie.hd %></td>
        <td><%= movie.threed %></td>
        <td><%= movie.digital %></td>
        <td><%= movie.watched %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path, class: 'btn btn-large btn-primary' %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to '<< Back', movies_path, :class => "btn btn-large" %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Sd:</strong>
  <%= @movie.sd %>
</p>

<p>
  <strong>Hd:</strong>
  <%= @movie.hd %>
</p>

<p>
  <strong>Threed:</strong>
  <%= @movie.threed %>
</p>

<p>
  <strong>Digital:</strong>
  <%= @movie.digital %>
</p>

<p>
  <strong>Watched:</strong>
  <%= @movie.watched %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/welcome/index.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Catalog</h1>

<div class="home-icons-width" style="height:200px; width: 300px; margin: 0 auto;">
<div class="home-icon"> <!--  style="background-color:#1d9c73;" -->
	<%= link_to '', books_path, class: "fa fa-book fa-5x" %>
</div>
<div class="home-icon">
	<i class="fa fa-film fa-5x"></i>
</div>
<div class="home-icon">
	<i class="fa fa-gamepad fa-5x"></i>
</div>
</div>

  <!-- <%= link_to 'Books', books_path, class: "btn btn-large btn-primary" %> -->
  <!-- <%= link_to 'Video Games', video_games_path, class: "btn btn-large btn-primary" %> -->
  <!-- <%= link_to 'Movies', movies_path, class: "btn btn-large btn-primary" %> -->
</div>